### ISSUE TITLE
Gearbox测试代码在IE8下适配总结

### ISSUE THREAD

**Issue by lyt9304** [CMUI/gearbox#18]
# Gearbox测试代码在IE8下适配总结
## 整体步骤
1. mocha支持IE8，但是chai不支持，所以需要找到代替的断言库，也就是expect.js
2. 换成expect.js后，对应的测试语句语法需要修改，有些没有的需要自己重写，比如deepEqual
3. 测试页面跑起来之后，看看所有代码中有哪些不能跑的代码，一一修改
   - history.replaceState不支持
   - Date.now不支持
   - Action中的Dom Binding有谜之bug
   - Template中有谜之bug
### 搭建环境，阅读代码
1. IE8的测试机不能跑，所以只能用vmware跑modernie来搭建测试环境。
2. bower install && npm install
3. 阅读gearbox的src代码以及action的代码，熟悉underscore库的语法
### 找寻代替的断言库
1. 查找后发现expect.js可以支持IE8，所以就写了简单的测试套件，放在IE8下运行后通过
2. 分别查看chai的api和expect的api，发现测试所用到的基本断言都是可以代替的，并且expect的eql接口和deepEqual其实原理是差不多的，只不过递归判断的时候需要全等，所以改写是相对比较容易得。
### 改写测试代码，重写deepEqual
1. 断言库改变了之后有一些chai的语法要修改到expect去，如下：
   - .to.be.true=>.to.equal(true)
   - .to.be.false=>.to.equal(false)
   - .to.be.undefined=>.to.equal(undefined)
   - .to.deep.equal()=>.to.deepEqual()
2. 实现deepEqual
   - 首先想了比较多的情况，写了chai版本和expect版本的两个测试集，只要最后改的deepEqual能够将这个测试集完全通过，就可以说基本模拟了chai的deep.equal的接口
   - 分析了deepEqual所可能的情况
   - 阅读expect.js的源代码，了解他的构造，然后在内部添加所需要的deepEqual方法
   - 可以看到eql方法其实思路和deep equal的思路是一样的，只不过expect.js的eql方法对于类型没有卡死，只要==满足就可以了，这和我们需要的是不一样的，所以其实只要以eql的代码为基础修改一下某一些情况下的判断就可以了。
   - 通过deepeql测试集
### 修改测试代码适配到IE8
1. Date.now不支持
   
   now方法IE8不支持，所以加入polyfill
   
   ``` javascript
   if (!Date.now) {
         Date.now = function now() {
           return new Date().getTime();
         };
       }
   ```
2. Action中的Dom Binding有谜之bug
   - 这里的bug不是很容易发现，一步步调试过来之后发现，不知道为什么在action模块的getActionName方法调用后，actionName并没有被取出来，是个空字符串。最后定位到了action模块中的.data()这个接口上。
   - 这个bug在使用zepto的时候没有发生，但是在jquery下就发生了。
   - 阅读jquery的data接口的相关代码，发现了jquery在调用dataapi的时候回经过缓存cache对象。
   - 最后发现在赋值data-action的时候，使用的是attr("data-action",value)这个接口，但是取的时候使用的是data接口
   - 也就是说存的时候调用attr，但是没有将新的data值存到缓存池中，但是在取的时候用data接口，却是从缓存池里拿出来的，所以这个值就丢掉了。
   - 所以这个问题通过统一存取的接口就可以fix了。
   - 最后结论：**统一使用attr去存取**
3. Template中有谜之bug
   - 这个bug是因为script标签创造出来后，调用jquery的text的方法，最后就会调用原生的createTextNode，然后这个方法如果实在script标签下调用的话，IE8下面会有bug
   - 用原生的方法去添加一个script标签
   
   ``` javascript
   var body= document.getElementsByTagName('body')[0]; 
   var script1= document.createElement('script'); 
   script1.type= SCRIPT_TYPE; 
   script1.id=PREFIX + TEMPLATE_ELEM_ID_1;
   script1.text= templateCode1; 
   body.appendChild(script1); 
   ```
4. history.replaceState不支持
   - 先尝试用了polyfill的方式，找到了history.js，尝试之后由于是通过改变hash值来完成的，所以最后url会变得很乱，就无法测试函数功能了，这条路就是走不通的。
   - 乱七八糟想了很多
   - 在鹏哥的提示下尝试了用iframe的方式，其实已经想到了，但是没有往这个方面多考虑一下，而是一直再想怎么自己造一个window来欺骗action
   - iframe的主要思路是：
     - 在测试页面插一个iframe，然后所有的跳转都在iframe中进行
     - 每次要跳转页面的时候，自动分配一个testID，并和url一起加到iframe的url中，进行跳转
     - 将回调函数以testID为key注册到regesteredTests中
     - 将需要测试的param通过window.name赋给iframe，这样就可以在iframe的脚本中拿到需要测试的数据
     - 在测试页面注册对应onMessage操作，当收到iframe发来的结果后，根据testID去执行相应的回调函数
     - 在iframe中执行_.url.getParam的操作后，将记录下来的结果以及本次分配的testID，通过postMessage的方式传回给原来的测试页面
     - 触发测试页面的回调函数，将测试结果与预期结果进行比较
   - 坑：global leak
     
     这个坑是因为，通过jquery创造iframe的时候，jquery创造了一个全局变量就是这个iframe的id，然后指向iframe这个dom元素，但是这个在mocha中不被允许，他怕你在写代码中无意创造了全局变量，为了提醒你，所以会报global leak的错，所以在一开始的时候就设定好sandbox是我刻意创造出的全局变量就可以了
     
     ``` javascript
     $(function(){
         mocha
             .globals(['sandbox'])
             .run()
     })
     ```
   - 坑：JSON格式中不能够使某个key对应的value为undefined
     
     由于这个原因从iframe传参数回来的时候回导致value未undefine的key会丢失，但是由于IE8下的postMessage接口只能传递字符串，所以说没有很好的方法解决，只能暂时通过数组记录undefined的那些key，然后传回测试页面的方法来还原测试结果

**Comment by cssmagic** [comment]
> - 阅读expect.js的源代码，了解他的构造，然后在内部添加所需要的deepEqual方法
> - 可以看到eql方法其实思路和deep equal的思路是一样的，只不过expect.js的eql方法对于类型没有卡死，只要==满足就可以了，这和我们需要的是不一样的，所以其实只要以eql的代码为基础修改一下某一些情况下的判断就可以了。

如果要求不是特别严格的话，或者说，不会踩到类型转换的坑的话，可以直接拿 expect.js 的 `.eql()` 来用。这样可以省很多事情。

**Comment by cssmagic** [comment]
> 这个坑是因为，通过jquery创造iframe的时候，jquery创造了一个全局变量就是这个iframe的id……

这应该不是 jQuery 的坑，因为在其它浏览器下不出现。把 iframe 的 id 映射为一个全局变量应该是 IE 的行为。

**Comment by cssmagic** [comment]
此工作已完成，感谢你的努力！ :clap:
